apiVersion: v1
kind: Pod
metadata:
  name: var-finetune-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
    - name: var-finetune
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /opt/repo/VARfork
      command:
        - "bash"
        - "-c"
      args:
        - |
          # --- User and Environment Setup ---
          echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
          
          # --- Git Repository Setup ---
          echo "Setting up VAR repository..."
          cd ${REPO_PATH}
          git pull origin main || echo "Repository already exists, continuing"
          
          # --- Install required dependencies ---
          echo "Installing required dependencies..."
          pip install -r ${REPO_PATH}/requirements.txt
          pip install torch~=2.1.0 Pillow numpy
          
          # --- Extract PAP dataset ---
          echo "Extracting PAP dataset..."
          mkdir -p ${HOME}/pap_data
          if [ -f "/data/pap_data.tar" ]; then
            echo "Found .tar file, extracting..."
            tar -xf /data/pap_data.tar -C ${HOME}
          else
            echo "Searching for alternative archive formats..."
            find /data -name "*.tar*" -o -name "*.zip" | head -1 | xargs -I {} bash -c "echo 'Extracting {}...' && if [[ {} == *.zip ]]; then unzip {} -d ${HOME}; else tar -xf {} -C ${HOME}; fi"
          fi
          
          # --- Run VQ-VAE finetuning ---
          echo "Starting VQ-VAE finetuning..."
          cd ${REPO_PATH}
          python finetune_vqvae.py \
            --data_path=${HOME}/pap_data \
            --pretrained=vae_ch160v4096z32.pth \
            --batch_size=32 \
            --lr=1e-4 \
            --epochs=50 \
            --save_dir=${REPO_PATH}/pap_checkpoints \
            --image_size=256 \
            --workers=4
          
          echo "Finetuning completed or encountered an error."
          echo "Pod is now idle. Connect with: kubectl exec -it var-finetune-pod -- bash"
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: pap-data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 30Gi
          cpu: "16"
          nvidia.com/gpu: "6"
        requests:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "6"
  initContainers:
    - name: init-git-repo
      image: alpine/git
      args:
        - clone
        - --single-branch
        - -b
        - main
        - https://github.com/tsereda/VARfork.git
        - /opt/repo/VARfork
      volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          memory: 256Mi
          cpu: 200m
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: pap-data-volume
      persistentVolumeClaim:
        claimName: pap-data
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  restartPolicy: Never